spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5433/ampm
spring.datasource.username=ampm
spring.datasource.password=ampm
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
